### ISSUE TITLE
Web Page not responsive

### ISSUE THREAD

**Issue by rexayyy** [roboflow-ai/roboflow-python#45]
I am trying to upload annotated dataset on roboflow but it takes a lot of time and becomes unresponsive at the end and all the files are being lost and i have to upload them again from the start. I have tried several times but i am unable to upload the data.

**Comment by rexayyy** [comment]
![image](https://user-images.githubusercontent.com/97718899/185748832-8d99fc17-1afc-4e1f-8fbc-5f28279eb7b2.png)

**Comment by mo-traor3-ai** [comment]
Hi @rexayyy, can you report this bug to help@roboflow.com with details such as project type, annotation format, the account email you signed up with, and the number of images + dataset size in MB or GB?

This repo is for the Python package, rather than bug reports for the main app.

**Comment by FrancescoSaverioZuppichini** [comment]
@mo-traor3-ai do you think we can close this?
