### ISSUE TITLE
Kindly update urllib 3 in Roboflow, it clashes with wanb package

### ISSUE THREAD

**Issue by magedhelmy1** [roboflow-ai/roboflow-python#72]
To replicate the issue:

First ` pip install roboflow `followed by `pip install wanb`

The error is 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
roboflow 0.2.17 requires urllib3==1.26.6, but you have urllib3 1.26.12 which is incompatible.
```

Downgrading can be an issue because it starts clashing with other libraries

`sentry-sdk 1.10.1 requires urllib3>=1.26.11; python_version >= "3.6", but you have urllib3 1.26.6 which is incompatible.`

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @magedhelmy1 , sorry for the late reply. We have changed the version to be `>=1.26.6`, it should work now. It will be include in the next release, in the meantime you can install it using git

```
pip install git+https://github.com/roboflow-ai/roboflow-python.git
```
